### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Thomananas** [pauberson/MultiuserVive#3]
Hey pauberson,

I am a beginner in Unity. I have a project with a scene and which is working fine in VR. But i do not understand how to integrate your project in mine. Is there any example how to do that or can you explain how please? :)
Thank you!

Best regards

**Comment by pauberson** [comment]
You could try exporting one of the scenes to a Unity package, then importing that into your own project:

1. Right-click on Scenes/LocalNetwork in the Project tab, Select Export package and save.
2. Open your project, select Assets/Import Package/Custom Package and choose the file you just saved.
3. Then copy & paste things between the scenes.
